name: fortress
description: >-
  Fortress is a package of game development utilities for Dart and Flutter apps. It includes
  renderers, an extensible game loop, basic UI elements, map generators and more!
version: 0.1.1-dev
homepage: https://alexgladd.github.io/fortress/
repository: https://github.com/alexgladd/fortress
issue_tracker: https://github.com/alexgladd/fortress/issues

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
  test: ^1.20.1
