name: fortress
description: A library of useful low-level game development utilities for Dart and Flutter apps.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
